# Generated by Django 4.1 on 2022-09-02 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dessert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=42)),
                ('Body', models.TextField()),
                ('Type', models.CharField(choices=[('east', 'East Dessert'), ('west', 'West Dessert')], max_length=4)),
                ('Available', models.BooleanField(blank=True, default=True)),
                ('Created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
