# Generated by Django 4.1 on 2022-09-04 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0004_alter_dessert_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dessert',
            name='Created_on',
            field=models.DateField(auto_now_add=True),
        ),
    ]
