# Generated by Django 4.1 on 2022-09-05 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0005_alter_dessert_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='dessert',
            name='Price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='dessert',
            name='Quantity',
            field=models.BigIntegerField(default=0),
        ),
    ]
