# Generated by Django 4.1 on 2022-09-05 19:45

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0008_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='color',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=18, samples=None),
        ),
    ]
