# Generated by Django 4.1 on 2022-09-05 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0010_photo_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='Name',
        ),
    ]
