# Generated by Django 4.1 on 2022-09-05 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0011_remove_photo_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dessert',
            new_name='Product',
        ),
    ]
