# Generated by Django 4.1 on 2022-09-05 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0012_rename_dessert_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Product.product'),
        ),
    ]
