# Generated by Django 4.1 on 2022-09-05 21:18

from django.db import migrations, models
import django_extensions.validators


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0013_photo_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='color',
            field=models.CharField(max_length=6, validators=[django_extensions.validators.HexValidator(length=6)]),
        ),
    ]
