# Generated by Django 4.1 on 2022-09-05 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0015_rename_color_photo_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='Name',
            new_name='Color',
        ),
    ]
