# Generated by Django 4.1 on 2022-09-05 21:34

import Product.models
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.validators


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0016_rename_name_photo_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='P',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Color', models.CharField(max_length=6, validators=[django_extensions.validators.HexValidator(length=6)])),
                ('Image', models.ImageField(blank=True, null=True, upload_to=Product.models.upload_path)),
                ('product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Product.product')),
            ],
        ),
    ]
