# Generated by Django 4.1 on 2022-09-05 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0017_p'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='Color',
            new_name='person',
        ),
        migrations.DeleteModel(
            name='P',
        ),
    ]
