# Generated by Django 4.1 on 2022-09-05 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0019_rename_person_photo_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='color',
            new_name='Color',
        ),
    ]
