# Generated by Django 4.1 on 2022-09-06 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0021_photo_cover'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='photo',
            unique_together={('product', 'Cover')},
        ),
    ]
