# Generated by Django 4.1 on 2022-09-06 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0022_alter_photo_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='photo',
            unique_together=set(),
        ),
    ]
