# Generated by Django 4.1 on 2022-09-11 14:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0023_alter_photo_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Price',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='Quantity',
            field=models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
