# Generated by Django 4.1 on 2022-09-11 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0024_alter_product_price_alter_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Type',
            field=models.CharField(choices=[('Used', 'used'), ('New', 'new'), ('Open Box', 'open box')], max_length=8),
        ),
    ]
