# Generated by Django 4.1 on 2022-09-11 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0025_alter_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Type',
            field=models.CharField(choices=[('Used', 'used'), ('New', 'new'), ('Open Box', 'open box')], default='New', max_length=8),
        ),
    ]
